[build]
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA fallback: any non-file path should serve index.html so React Router handles it
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
