[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/api/golemio-proxy/*"
  to = "/.netlify/functions/golemio-proxy/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200